version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    restart: unless-stopped
    volumes:
      - ./api:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres@db/db
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mdillon/postgis:11-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
