FROM node:10-alpine
LABEL maintainer="Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"

ENV NODE_ENV development

WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN npm install --quiet
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]